### ISSUE TITLE
Can't enable AntiCheat when dev.bukkit.org is down

### ISSUE THREAD

**Issue by Spirit55555** [gravitylow/AntiCheat#121]
`2012-12-19 14:47:24 [SEVERE] Error occurred while enabling AntiCheat v1.4 (Is it up to date?)
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 502 for URL: http://dev.bukkit.org/server-mods/anticheat/files.rss
    at net.h31ix.anticheat.update.Updater.read(Updater.java:617)
    at net.h31ix.anticheat.update.Updater.readFeed(Updater.java:566)
    at net.h31ix.anticheat.update.Updater.<init>(Updater.java:216)
    at net.h31ix.anticheat.Anticheat.setupUpdater(Anticheat.java:183)
    at net.h31ix.anticheat.Anticheat.onEnable(Anticheat.java:69)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:272)
    at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:254)
    at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:320)
    at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:299)
    at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:258)
    at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
    at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398)
    at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://dev.bukkit.org/server-mods/anticheat/files.rss
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at net.h31ix.anticheat.update.Updater.read(Updater.java:613)
    ... 15 more`

**Comment by gravitylow** [comment]
A result of how the auto-updater works. I've been meaning to add threading to the updater, so I'll give that a shot sometime soon. May I ask when this happened? Was dev.bukkit.org actually down or was your connection off?

**Comment by Spirit55555** [comment]
dev.bukkit.org was down, and showed a 502 error page. I can't remember the exact time, I believe it was just after the RB release.

**Comment by SuperSpyTX** [comment]
It was probably a brief moment.

I think the only trick here is what @h31ix said, just threading the check and then writing to console a friendly message about the updater not working.

**Comment by 3vi1** [comment]
I see this error right now, as dev.bukkit.org is down.

Quick workaround:  Add an entry to your hosts files so that dev.bukkit.org redirects to a non-existant ip address.  It will then start properly (it only crashes when the server responds with the 5xx errors).
