### ISSUE TITLE
Error with openinv

### ISSUE THREAD

**Issue by greeterone** [gravitylow/AntiCheat#169]
I got this error when im using OpenInv plugin with AnitCheat.
OpenInv (nevest version from bukkitdev)
AntiCheat (1.5.5)

00:16:47
 CONSOLE:
[SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.5
00:16:47
 CONSOLE:
java.lang.ArrayIndexOutOfBoundsException: 41

**Comment by SuperSpyTX** [comment]
Do you mind accessing to your server.log file and retrieving the stacktrace?

**Comment by greeterone** [comment]
Got something like this.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 41
    at org.bukkit.craftbukkit.v1_4_R1.inventory.CraftInventory.getContents(CraftInventory.java:56)
    at net.h31ix.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:66)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 23 more

Open Inv version 1.9.7

**Comment by gravitylow** [comment]
An openinv issue, it isn't AntiCheat's fault.
