### ISSUE TITLE
Chat Spam (console error)

### ISSUE THREAD

**Issue by xsonarx** [gravitylow/AntiCheat#183]
This error repeats its self spamming console. it didnt kick the player out of the game.
1 message only got through when spamming, name did get banned but didn't get kicked.
leaving the player to spam 1 msg in game but console like hell.

26.02 20:13:00 [Server] INFO at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
26.02 20:13:00 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
26.02 20:13:00 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
26.02 20:13:00 [Server] INFO at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
26.02 20:13:00 [Server] INFO at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:530)
26.02 20:13:00 [Server] INFO at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
26.02 20:13:00 [Server] INFO at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
26.02 20:13:00 [Server] INFO at net.h31ix.anticheat.manage.Backend$1.run(Backend.java:754)
26.02 20:13:00 [Server] INFO at net.h31ix.anticheat.manage.Backend.access$000(Backend.java:46)
26.02 20:13:00 [Server] INFO at net.h31ix.anticheat.manage.Backend.processChatSpammer(Backend.java:1080)
26.02 20:13:00 [Server] INFO java.lang.NullPointerException
26.02 20:13:00 [Server] WARNING Task #2411 for AntiCheat v1.5.6-DEV-b429 generated an exception
26.02 20:13:00 [Server] INFO [Member] alantan: Someone give me 500 so i can buy a fucking plot in creative!

**Comment by xsonarx** [comment]
glad i could help :) - ill upload the new build hopefully that's fixed :)
