### ISSUE TITLE
Build 465 doesn load and 464 throws error on opening hopperminecarts

### ISSUE THREAD

**Issue by blablubbabc** [gravitylow/AntiCheat#204]
this is the error with the latest (465 dev build) using 1.5.1:

00:53:18 [SEVERE] Could not load 'plugins/AntiCheat.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:255)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:132)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugins(CraftServer.java:239)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.reload(CraftServer.java:603)
        at org.bukkit.Bukkit.reload(Bukkit.java:184)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:187)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:523)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchServerCommand(CraftServer.java:512)
        at net.minecraft.server.v1_5_R2.DedicatedServer.am(DedicatedServer.java:261)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:214)
        at java.util.zip.ZipFile.<init>(ZipFile.java:144)
        at java.util.jar.JarFile.<init>(JarFile.java:153)
        at java.util.jar.JarFile.<init>(JarFile.java:117)
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:243)
        ... 13 more

So I tried build 464, which at least loaded, but when I or anyone else opens a minecart-hopper it prints this error:

00:59:12 [SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.7-DEV-b464
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:506)
        at net.minecraft.server.v1_5_R2.EntityPlayer.openMinecartHopper(EntityPlayer.java:534)
        at net.minecraft.server.v1_5_R2.EntityMinecartHopper.a_(SourceFile:51)
        at net.minecraft.server.v1_5_R2.EntityHuman.p(EntityHuman.java:777)
        at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:1089)
        at net.minecraft.server.v1_5_R2.Packet7UseEntity.handle(SourceFile:36)
        at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
        at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:578)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
        at org.bukkit.craftbukkit.v1_5_R2.inventory.CraftInventory.getContents(CraftInventory.java:58)
        at net.h31ix.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 18 more

**Comment by gravitylow** [comment]
465 Loads fine for me.

As far as the other error goes, it's actually a Bukkit bug that, thanks to your information I'm now working with the core team on fixing. Thanks a lot for the detailed report, I'll update this ticket with new info.

**Comment by gravitylow** [comment]
I've created a commit to fix this here https://github.com/h31ix/CraftBukkit-Bleeding/commit/9b31f183bdd3b214536cbdf16569e07f6c7d0271 but I'm still talking to the team about it; it turns out this is more of a deep-rooted issue inherent to the way the minecraft logic works and my change is really only a patch of the error itself.

**Comment by xsonarx** [comment]
CB: 2721
AC: 465

Loads fine here too.

**Comment by gravitylow** [comment]
Closing this ticket as it's unrelated to AntiCheat

**Comment by gravitylow** [comment]
Pulled to http://dl.bukkit.org/downloads/craftbukkit/view/02045_1.5.1-R0.1/
