### ISSUE TITLE
Citiziens - Postal plugin

### ISSUE THREAD

**Issue by Malachiel87** [gravitylow/AntiCheat#207]
I have installed Postal plugin (http://dev.bukkit.org/server-mods/postal/) , with anticheat enabled, it spam this error on console, is possible to fix?.
2013-04-06 09:30:00 [SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.7
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:506)
    at net.minecraft.server.v1_5_R2.EntityPlayer.openContainer(EntityPlayer.java:508)
    at org.bukkit.craftbukkit.v1_5_R2.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:193)
    at com.vodhanel.minecraft.va_postal.VA_postal.ping_central_postmaster_worker(VA_postal.java:783)
    at com.vodhanel.minecraft.va_postal.VA_postal.ping_central_postmaster(VA_postal.java:672)
    at com.vodhanel.minecraft.va_postal.VA_postal.heart_beat(VA_postal.java:231)
    at com.vodhanel.minecraft.va_postal.VA_postal$2.run(VA_postal.java:195)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:510)
    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at net.h31ix.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 17 more

**Comment by xsonarx** [comment]
Download the latest build shown here (it might fix your problem)

http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/artifact/target/AntiCheat.jar

**Comment by gravitylow** [comment]
This is a Bukkit bug that I fixed in the beta.

Please upgrade, and note https://github.com/h31ix/AntiCheat/issues/204

Closed because this isn't an AntiCheat bug.
