### ISSUE TITLE
Citizens2

### ISSUE THREAD

**Issue by ReikoKasumi** [gravitylow/AntiCheat#214]
Whenever a Sentry from Citizens2 attacks another entity this error comes up in the console.
But it doesn't affect gameplay. 

---

2013-04-10 16:02:02 [SEVERE] Could not pass event EntityDamageByEntityEvent to AntiCheat v1.5.7
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:84)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:372)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:396)
    at net.minecraft.server.v1_5_R2.EntityLiving.damageEntity(EntityLiving.java:694)
    at net.minecraft.server.v1_5_R2.EntityMonster.damageEntity(EntityMonster.java:39)
    at net.minecraft.server.v1_5_R2.EntityHuman.attack(EntityHuman.java:854)
    at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:106)
    at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:113)
    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:211)
    at net.citizensnpcs.npc.entity.EntityHumanNPC.l_(EntityHumanNPC.java:159)
    at net.minecraft.server.v1_5_R2.World.entityJoinedWorld(World.java:1356)
    at net.minecraft.server.v1_5_R2.WorldServer.entityJoinedWorld(WorldServer.java:614)
    at net.minecraft.server.v1_5_R2.World.playerJoinedWorld(World.java:1337)
    at net.minecraft.server.v1_5_R2.World.tickEntities(World.java:1225)
    at net.minecraft.server.v1_5_R2.WorldServer.tickEntities(WorldServer.java:480)
    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:560)
    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at net.h31ix.anticheat.event.EventListener.logCheat(EventListener.java:50)
    at net.h31ix.anticheat.event.EventListener.log(EventListener.java:41)
    at net.h31ix.anticheat.event.EntityListener.onEntityDamage(EntityListener.java:155)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 23 more

**Comment by gravitylow** [comment]
Fixed http://ci.gravitydevelopment.net/job/AntiCheat/474/
