### ISSUE TITLE
BlockBreakEvent

### ISSUE THREAD

**Issue by DevilXD** [gravitylow/AntiCheat#216]
I'm getting this error in console... It's appear, when I break a block, which is protected by WorldGuard... I'm not sure, what is in unprotected areas...

2013-04-17 13:40:44 [SEVERE] Could not pass event BlockBreakEvent to AntiCheat v1.5.7
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.v1_4_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:282)
    at net.minecraft.server.v1_4_R1.PlayerInteractManager.a(PlayerInteractManager.java:209)
    at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:567)
    at net.minecraft.server.v1_4_R1.Packet14BlockDig.handle(SourceFile:46)
    at com.lishid.orebfuscator.internal.v1_4_R1.Packet14Orebfuscator.handle(Packet14Orebfuscator.java:20)
    at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
    at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NoSuchFieldError: DROPPER
    at net.h31ix.anticheat.util.BlockHardness.<clinit>(BlockHardness.java:46)
    at net.h31ix.anticheat.util.Utilities.calcSurvivalFastBreak(Utilities.java:339)
    at net.h31ix.anticheat.manage.Backend.checkFastBreak(Backend.java:636)
    at net.h31ix.anticheat.event.BlockListener.onBlockBreak(BlockListener.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 17 more

http://pastebin.com/1dAPs6F9

PS.: I'm polish, sorry for my english...

**Comment by gravitylow** [comment]
AntiCheat 1.5.7 is for MC 1.5.1, not MC 1.4.7

**Comment by DevilXD** [comment]
Strange... I was sure that I downloaded right version... My fault... I changed to the right  verison, and it's everything fine... Thanks for help :)  Closed...
