### ISSUE TITLE
console error dev build 499

### ISSUE THREAD

**Issue by dutchy1001** [gravitylow/AntiCheat#250]
At first start up with the dev build 499 it gave me this error in console

2013-09-29 15:39:09 [INFO] [AntiCheat] Enabling AntiCheat v1.5.9-DEV-b499
2013-09-29 15:39:09 [SEVERE] Error occurred while enabling AntiCheat v1.5.9-DEV-b499 (Is it up to date?)
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at net.h31ix.anticheat.config.files.Magic.open(Magic.java:419)
    at net.h31ix.anticheat.config.ConfigurationFile.load(ConfigurationFile.java:85)
    at net.h31ix.anticheat.config.ConfigurationFile.<init>(ConfigurationFile.java:63)
    at net.h31ix.anticheat.config.ConfigurationFile.<init>(ConfigurationFile.java:49)
    at net.h31ix.anticheat.config.ConfigurationFile.<init>(ConfigurationFile.java:45)
    at net.h31ix.anticheat.config.files.Magic.<init>(Magic.java:354)
    at net.h31ix.anticheat.config.Configuration.<init>(Configuration.java:48)
    at net.h31ix.anticheat.manage.AnticheatManager.<init>(AnticheatManager.java:62)
    at net.h31ix.anticheat.AntiCheat.onEnable(AntiCheat.java:55)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_6_R3.MinecraftServer.l(MinecraftServer.java:315)
    at net.minecraft.server.v1_6_R3.MinecraftServer.f(MinecraftServer.java:292)
    at net.minecraft.server.v1_6_R3.MinecraftServer.a(MinecraftServer.java:252)
    at net.minecraft.server.v1_6_R3.DedicatedServer.init(DedicatedServer.java:152)
    at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:393)
    at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

any chance you can tell us more when it's been updated for 1.6.4?

**Comment by gravitylow** [comment]
Something is wrong with your HEAL_TIME_MIN value in the magic.yml file. Can you please paste that value and/or your whole magic.yml file so I can diagnose the issue?

**Comment by dutchy1001** [comment]
hi,

Thx for the quick reply. Here the magic.yml  as you requested

ANIMATION_MIN: 200
ASCENSION_COUNT_MAX: 8
BLOCK_BREAK_MIN: 0.1
BLOCK_MAX_DISTANCE: 5.5
BLOCK_MAX_DISTANCE_CREATIVE: 6.0
BLOCK_PLACE_MIN: 0.1
BLOCK_PUNCH_MIN: 5
BOW_ERROR: 0.25
CHAT_BAN_LEVEL: 3
CHAT_KICK_LEVEL: 10
CHAT_MIN: 100
CHAT_REPEAT_MIN: 260
CHAT_WARN_LEVEL: 7
DAMAGE_TIME: 3000
DROP_CHECK: 10
DROPPED_ITEM_TIME: 100
DROP_TIME_MIN: 800
EAT_TIME_MIN: 1000L
ENTERED_EXITED_TIME: 1000
ENTITY_MAX_DISTANCE: 5.5
ENTITY_MAX_DISTANCE_CREATIVE: 6.0
EXIT_FLY_TIME: 2000
EXPLOSION_DAMAGE_TIME: 5000
FASTBREAK_LIMIT: 2
FASTBREAK_MAXVIOLATIONS: 2
FASTBREAK_MAXVIOLATIONS_CREATIVE: 4
FASTBREAK_MAXVIOLATIONTIME: 10000
FASTBREAK_TIMEMAX: 1000
FASTBREAK_TIMEMAX_CREATIVE: 100
FASTPLACE_MAXVIOLATIONS: 2
FASTPLACE_MAXVIOLATIONS_CREATIVE: 3
FASTPLACE_MAXVIOLATIONTIME: 10000
FASTPLACE_TIMEMIN: 50
FASTPLACE_ZEROLIMIT: 3
FLIGHT_BLOCK_LIMIT: 15.0
FLIGHT_LIMIT: 150
HEAL_TIME_MIN: 2000L
INSTANT_BREAK_TIME: 2
INVENTORY_CHECK: 10
INVENTORY_TIMEMIN: 50
JOIN_TIME: 2000
KNOCKBACK_DAMAGE_TIME: 4000
LADDER_Y_MAX: 0.11761
LADDER_Y_MIN: 0.11759
NOFALL_LIMIT: 9
PROJECTILE_CHECK: 10
PROJECTILE_TIME_MIN: 1500
SNEAK_TIME: 250
SPEED_MAX: 3
SPRINT_FOOD_MIN: 6
SPRINT_MIN: 0.2
TELEPORT_MIN: 400
TELEPORT_TIME: 1000
TIMER_STEP_CHECK: 50
TIMER_TIMEMIN: 2000
VELOCITY_CHECKTIME: 2100
VELOCITY_MAXTIMES: 2
VELOCITY_PREVENT: 5000
VELOCITY_SCHETIME: 2
VELOCITY_TIME: 3
WATER_ASCENSION_VIOLATION_MAX: 13
WATER_CLIMB_MAX: 0.15
WATER_SPEED_VIOLATION_MAX: 4
XZ_SPEED_MAX: 0.25
XZ_SPEED_MAX_FLY: 0.56
XZ_SPEED_MAX_POTION: 0.7
XZ_SPEED_MAX_SNEAK: 0.15
XZ_SPEED_MAX_SOULSAND: 0.12
XZ_SPEED_MAX_SOULSAND_SPRINT: 0.15
XZ_SPEED_MAX_SPRINT: 0.65
XZ_SPEED_MAX_WATER: 0.19
XZ_SPEED_MAX_WATER_SPRINT: 0.3
Y_MAXDIFF: 5
Y_MAXVIOLATIONS: 1
Y_MAXVIOTIME: 5000
Y_SPEED_MAX: 0.5
Y_TIME: 1000
VERSION: 0.2
XZ_SPEED_MAX_SOULSAND_POTION: 0.16

This file has never been changed by me, but at the line you mentioned "HEAL_TIME_MIN" the value has an L behind it what I think might be the mistake because all other value's are in orange(notepad++) and this one isn't.

Edit: Just found  that EAT_TIME_MIN also has an L behind it.

**Comment by dutchy1001** [comment]
Deleted the configs and restarted the server, problem solved. 
The new magic.yml doen't have the L behind the value's. Not sure how or why they were there as I never changed those value's

Thx for pointing me in the right direction
