### ISSUE TITLE
Taming a cat with mcMMO causes an error

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#55]
This seems to cause an error in the latest dev build 181. I am using this version of mcMMo v1.3.09-dev-b901 I tried updating to newer ones but they fail. I believe it is the build which says it adds support for AntiCheat.

2012-06-11 10:07:07 [SEVERE] Could not pass event PlayerInteractEvent to AntiCheat
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
        at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:287)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:636)
        at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:119)
        at net.minecraft.server.Packet15Place.handle(SourceFile:39)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:83)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchMethodError: com.gmail.nossr50.mcMMO.getPlayerProfile(Lorg/bukkit/OfflinePlayer;)Lcom/gmail/nossr50/datatypes/PlayerProfile;
        at net.h31ix.anticheat.util.Utilities.isUsingMcMMOAbility(Utilities.java:100)
        at net.h31ix.anticheat.manage.Backend.checkLongReachBlock(Backend.java:162)
        at net.h31ix.anticheat.event.PlayerListener.onPlayerInteract(PlayerListener.java:176)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        ... 14 more

**Comment by ghost** [comment]
Actually now that I have more than me on, it seems to be happening constantly for almost any mcMMO ability. This didn't happen with a previous version of AntiCheat I was using before with this version of mcMMO if that helps.

**Comment by SuperSpyTX** [comment]
Try again with the newer builds of McMMO and give logs for that.

**Comment by ghost** [comment]
Yeah, well I tried a newer build but that completely broke the server. However, the permissions are wonky anyway for some reason with it as it is and all the abilities are disabled, otherwise everyone gets everything but it was not like that in the past. I can test it on a dev server though when I get a chance.

**Comment by gravitylow** [comment]
The newest mcMMO and newest AntiCheat (dev builds) are compatible.

**Comment by mbax** [comment]
![Meow](http://i.imgur.com/9kN8t.jpg)

**Comment by SuperSpyTX** [comment]
So any luck of trying to get latest dev of McMMO? @ty2u

**Comment by ghost** [comment]
Hey =) Well I have tested it for awhile and I believe it does work  with AntiCheat. The super breaker thing seemed to work fine and all the other stuff I played with for awhile.

Some of my mcMMO permissions might have been in the wrong order with PEX and MonsterIRC seems to have died with the latest mcMMO but maybe mcMMO just has to get more stable from all its changes and/or other plugins have to catch up still.

**Comment by gravitylow** [comment]
Ok cool. Closing then :) And FYI, it was an issue of an API upgrade on the mcMMO side (as far as we can tell) that caused this issue. We immediately updated AntiCheat, but unfortunately the update made it incompatible with past versions, as you have seen.
