### ISSUE TITLE
Console Error Messages

### ISSUE THREAD

**Issue by MatthewStellato** [gravitylow/AntiCheat#56]
I installed this plugin and in game there seems to be no problems with it and it works fine, but when I look at the console, there are constant errror messages that say stuff like
[SEVERE] Could not pass PlayerMoveEvent to Anticheat
code gibberish
code gibberish
code gibberish
code gibberish
and so on...
And this happens every time someone moves and after about 3 days the server.log goes from a few hundred mbs to like a gb.  I know this isn't because anticheat isn't a reliable plugin, because so many of my friends use it seamlessly on their servers, so I was just wondering if there was maybe a conflict with one of my other plugins, so here is a list of all the plugins i have:
GroupManager, Essentials, SimplyVanish, WorldGuard, WorldEdit, ChannelChat, AutoAnnouncer, Factions, Herobrine, Lockette, Logblock, MobDisguise, NoLagg, MineQuery, SWatchDog (this might be it), ShiftMode, ManySmallTweaks, SimpleHat, Stargate, mcMMO, AlphaChest, and BKCommonLib.
If there aren't any conflicts with these, is this a common issue? or do you know anything about how to fix it?

**Comment by gravitylow** [comment]
If you want help we kind of need that "code gibberish" and your version number.

**Comment by MatthewStellato** [comment]
I am running CB 1.2.5-R4.0 and this is just an example of one of the errors

"2012-06-12 16:43:44 [SEVERE] Could not pass event PlayerInteractEvent to AntiCheat
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:94)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:537)
at net.minecraft.server.Packet14BlockDig.handle(SourceFile:43)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchFieldError: p
at net.h31ix.anticheat.util.Utilities.isUsingMcMMOAbility(Utilities.java:100)
at net.h31ix.anticheat.manage.Backend.checkLongReachBlock(Backend.java:161)
at net.h31ix.anticheat.event.PlayerListener.onPlayerInteract(PlayerListener.java:176)
at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
...12 more"

**Comment by gravitylow** [comment]
Use the latest dev build of anticheat and the latest dev build of mcMMO.

http://ci.h31ix.net/
http://ci.mcmmo.org/
