### ISSUE TITLE
NPE when network connection not  fully reliable

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#84]
Need to check for null and handle gracefully.

17:32:37 [SEVERE] Error occurred while enabling AntiCheat v1.3.2-DEV-b205 (Is it up to date?)
java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:61)
    at java.io.BufferedReader.<init>(BufferedReader.java:76)
    at java.io.BufferedReader.<init>(BufferedReader.java:91)
    at net.h31ix.anticheat.Anticheat.checkForUpdate(Anticheat.java:299)
    at net.h31ix.anticheat.Anticheat.onEnable(Anticheat.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:381)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:368)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:197)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by SuperSpyTX** [comment]
I'll have @h31ix or possibly I add it.
